repositories:
 - name: bitnami
   url: https://charts.bitnami.com/bitnami

releases:
- name: kafka-prod
  namespace: prod
  chart: bitnami/kafka
  version: "^23.0.6"
  values:
  - ./values/kafka-prod.yaml
- name: kafka-dev
  namespace: dev
  chart: bitnami/kafka
  version: "^23.0.6"
  values:
    - ./values/kafka-dev.yaml