apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-csi-s3-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: kube-csi-s3