apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: kube-csi-s3-secret
stringData:
  accessKeyID: YCAJEOdV1doswJ7bYoqvZxRqP
  secretAccessKey: YCN2NcjKlPF9liQgZmBTQmJhMvc9gPeU0unMEO6a
  endpoint: https://storage.yandexcloud.net/