apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: homework
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccount: mysql
      containers:
      - name: mysql-operator
        image: roflmaoinmysoul/mysql-operator:1.0.0