apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-metrics-exporter
  namespace: kube-metrics
  labels:
    app: kube-metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-metrics-exporter
  template:
    metadata:
      labels:
        app: kube-metrics-exporter
    spec:
      serviceAccountName: kube-metrics-monitor
      containers:
      - name: kube-metrics-exporter
        image: itzg/kube-metrics-exporter
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace