apiVersion: v1
kind: Service
metadata:
  name: kube-metrics-exporter-service
  namespace: kube-metrics
spec:
  type: ClusterIP
  selector:
    app: kube-metrics-exporter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080