apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  namespace: homework
  labels:
    app: nginx-distroless
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 101
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless:latest
    securityContext:
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-conf