apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2024-04OTUS/niko2892_repo.git
    targetRevision: HEAD
    path: kubernetes-networks
  destination: 
    server: https://kubernetes.default.svc
    namespace: homework