{{- range .Values.serviceAccount  }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{  .metadata.name  }}
  namespace: {{  .metadata.namespace  }}
---
{{- end  }}
---
{{- range .Values.clusterRole  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:  
  name: {{  .metadata.name  }}
rules:
  {{-  toYaml .rules | nindent 4  }}
---
{{- end  }}
---
{{- range .Values.clusterRoleBinding  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{  .metadata.name  }}
subjects:
  {{-  toYaml .subjects | nindent 4  }}
roleRef:
  kind: {{  .roleRef.kind  }}
  name: {{  .roleRef.name  }}
  apiGroup: {{  .roleRef.apiGroup  }}
---
{{- end  }}
---
{{- range .Values.role  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:  
  name: {{  .metadata.name  }}
  namespace: {{  .metadata.namespace  }}
rules:
  {{-  toYaml .rules | nindent 4  }}
---
{{- end  }}
---
{{- range .Values.roleBinding  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{  .metadata.name  }}
  namespace: {{  .metadata.namespace  }}
subjects:
  {{-  toYaml .subjects | nindent 4  }}
roleRef:
  kind: {{  .roleRef.kind  }}
  name: {{  .roleRef.name  }}
  apiGroup: {{  .roleRef.apiGroup  }}
---
{{- end  }}