apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{name}"
rules:
- apiGroups: ["otus.{namespace}"]
  resources: ["mysqls"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["Services","persistentVolumes","persistentvolumeClaims"]
  verbs: ["create", "delete"]