apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{name}"
subjects:
  - kind: ServiceAccount
    name: "{name}"
    namespace: "{namespace}"
roleRef:
  kind: ClusterRole
  name: "{name}"
  apiGroup: rbac.authorization.k8s.io