apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{name}"
  namespace: "{namespace}"
  labels:
    app: "{name}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{name}"
  template:
    metadata:
      labels:
        app: "{name}"
    spec:
      serviceAccount: "{name}"
      containers:
      - name: "{name}"
        image: "{image}"
        env:
        - name: "MYSQL_ROOT_PASSWORD" 
          value: "{password}"
        - name: "MYSQL_DATABASE"
          value: "{database}"
        ports:
        - containerPort: {container_port}
      volumeMounts:
        - name: shared-data
          mountPath: /var/lib/mysql
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: "{name}"
