apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{namespace}"
  name: "{name}"
subjects:
  - kind: ServiceAccount
    name: "{name}"
    namespace: "{namespace}"
roleRef:
  kind: Role
  name: "{name}"
  apiGroup: rbac.authorization.k8s.io