apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
spec:
  initContainers:
  - name: init-container
    image: busybox:1.36.1
    command: ["/bin/sh", "-c", "echo Hello, world! > /init/index.html"]
    volumeMounts:
    - name: shared-data
      mountPath: /init
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-data
      mountPath: /homework
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
    lifecycle:
      preStop:
        exec:
          command: ["rm", "-f", "/homework/index.html"]
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: nginx-conf
    configMap:
        name: nginx-conf